name: Biweekly Scraper Execution

on:
  schedule:
    # Runs at 00:00 UTC every 15 days
    - cron: '0 0 */15 * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Dependencies
      run: |
        pip install selenium pandas gspread numpy webdriver-manager
        # Add any other dependencies your script needs

    - name: Run Scraper Script
      run: |
        python scraper1.py
      # Make sure 'scraper1.py' is the correct path to your script in the repository
